services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    environment:
      KEY: "d9e90f62050850c00b15b31e9a85c127c43395625efba6ac2d5391c973e498b7"
      ADMIN_EMAIL: "admin@englishsponge.com"
      ADMIN_PASSWORD: "adminadmin"      # Change this to something secure!
      DB_CLIENT: "pg"
      DB_HOST: "host.docker.internal" # If your Postgres runs on the host machine
      DB_PORT: "5432"
      DB_DATABASE: "englishsponge"             # Change to your database name
      DB_USER: "ayush"             # Change to your database user
      DB_PASSWORD: "mcd@2023"         # Change to your database password
    restart: always